name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"
      - uses: leafo/gh-actions-luarocks@v4
      - name: Install busted and luacheck
        run: |
          luarocks install busted
          luarocks install luacheck
      - name: Lint
        run: luacheck .
      - name: Test
        run: busted
